### ISSUE TITLE
CDF5 support in netCDF will be optional with next release.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf4-python#713]
[See this netcdf-c issue for more information](https://github.com/Unidata/netcdf-c/issues/484).

Starting with the upcoming 4.5.0-rc3 and moving forward, CDF5 support will be a configure time option.  There are currently a couple of issues with it that are blocking the 4.5.0-rc3 release, and adding a way to disable support has eased the logistics of getting the release out while addressing the issue.

`nc-config` has a new option, `nc-config --has-cdf5` which will return whether or not libnetcdf supports CDF5.   Let me know if there's anything I can do to help make this easy for the python library to adapt to.

**Comment by jswhit** [comment]
Right now the python install script checks to see if `netcdf.h` has `#define NC_FORMAT_64BIT_DATA` in it - if so, CDF5 support is enabled.   Will this approach still work in 4.5.0?

**Comment by WardF** [comment]
It will not.  We also distribute `netcdf_meta.h`, I can add something in there along the lines of `#define HAS_CDF5`, let me take a look at it.

**Comment by jswhit** [comment]
Just tried running with `v4.5.0-release-branch` using `--disable-cdf5` - it compiles fine, but as expected `tst_cdf5.py` fails.  I don't think this is too big a deal though.

**Comment by WardF** [comment]
Sounds good; it's an expected failure of course, and if it isn't a problem for the netcdf4-python package, it isn't a problem for us.  I wanted to say something ahead of time, however. I'm starting to prep the rc3 release today.

**Comment by jswhit** [comment]
If you can add HAS_CDF5 in netcdf_meta.h that would be helpful - that way I can disable the test if it is set.

**Comment by WardF** [comment]
Done; currently in the `v4.5.0-release-branch` but will be migrated out to master shortly.

**Comment by ArchangeGabriel** [comment]
@jswhit Can you disable the test if NetCDF is compiled without CDF5? This is the only test failure we see in our builds here, and we would like to avoid having to add a special case handling for this in our build process. ;)

**Comment by jswhit** [comment]
It's done it github master

**Comment by ArchangeGabriel** [comment]
How is `__has_cdf5_format__` determined? Because 1.3.1 still fails here:
```
======================================================================
ERROR: runTest (tst_cdf5.test_cdf5)
testing NETCDF3_64BIT_DATA format (CDF-5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-netcdf4/src/netCDF4-1.3.1/test/tst_cdf5.py", line 19, in setUp
    v = nc.createVariable('var',np.uint8,'dim')
  File "netCDF4/_netCDF4.pyx", line 2437, in netCDF4._netCDF4.Dataset.createVariable
  File "netCDF4/_netCDF4.pyx", line 3389, in netCDF4._netCDF4.Variable.__init__
  File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

----------------------------------------------------------------------
```

**Comment by jswhit** [comment]
if `#define NC_HAS_CDF5` exists in `netcdf_meta.h`

**Comment by ArchangeGabriel** [comment]
Exists? Not the actual value? I’ve got this:
```
#define NC_HAS_CDF5      0  /*!< CDF5 support. */
```

**Comment by jswhit** [comment]
Oops. My understanding is that if CDF5 was not enabled, there would be no NC_HAS_CDF5 in nc_meta.h.  I'll fix that.

**Comment by jswhit** [comment]
pull request #736

**Comment by jswhit** [comment]
pull request #736 merged, closing again
